#!/bin/bash
sqlite3 server/most demo.db "update voip_turnserver set address = "192.168.1.109" where id = 1"
sqlite3 server/most demo.db "update voip_sipserver set address = "192.168.1.109" where id = 1"
sqlite3 server/most demo.db "update provider_client set url = \"http://192.168.1.109\" and redirect_uri = \"http://192.168.1.109\" where id = 1"